Runnect/Runnect-iOS

- Runnect-iOS/Podfile
- Runnect-iOS/Podfile.lock
- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Global/Extension/Foundation+/Encodable+.swift
- Runnect-iOS/Runnect-iOS/Global/Utils/LoadingIndicator.swift
- Runnect-iOS/Runnect-iOS/Global/Utils/Toast.swift
- Runnect-iOS/Runnect-iOS/Global/Utils/adjusted+.swift
- Runnect-iOS/Runnect-iOS/Info.plist
- Runnect-iOS/Runnect-iOS/Network/Foundation/NetworkLoggerPlugin.swift
프로젝트 세팅했습니다.
- ClientId 추가
- Extension, Utils 추가 및 수정
- 없습니다.
| ex. 로그인 화면 | 파일첨부바람 |
- 생략
- Resolved: #4
> [Setting] #4 - 프로젝트 세팅

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Global/Literal/ColorLiterals.swift
- Runnect-iOS/Runnect-iOS/Global/Supports/SceneDelegate.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingHomeVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/TabBar/TaBarController.swift
- MyPageVC UI 구현
- NavigationBar를 추가했어용
- Profile과 Running Progress Layout을 구현했어용
- 목표 보상, 활동 기록, 업로드한 코스 Layout을 구현했어용
| 마이 페이지 |  <img src = "https://user-images.githubusercontent.com/79050615/210208150-2b59acda-4c6f-481d-9a73-ab32cb26172b.png" width="307"> |
- Resolved: #11
> [Feat] #11 - MyPageVC UI 구현

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Global/Literal/FontLiterals.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CountDownVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingHomeVC.swift
- CountDownVC 구현
- 디자이너분들이 원하신 애니메이션이 이게 맞는지는 모르겠는데 우선 카운트 다운에 애니메이션을 추가했습니다.
| 카운트 다운 | ![Simulator Screen Recording - iPhone 14 - 2023-01-03 at 01 39 26](https://user-images.githubusercontent.com/77267404/210258885-3824530c-7fd9-4e32-9a69-b1eddd8a4096.gif) |
- Resolved: #18
> [Feat] #18 - CountDownVC 구현

- README.md
- 리드미 작성
- 중간과제를 위한 리드미 작성했습니다. 추가하고 싶은 사항 있으면 이야기 해주세요~!
- 생략
- Resolved: #21
> [Docs] #21 - 리드미 작성

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Global/Literal/ColorLiterals.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoTableView/ActivityRecordInfoModel.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoTableView/ActivityRecordInfoTVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
- ActivityRecordInfo VC UI 구현
- StackView를 많이 사용했습니다..
- dummy 이미지가 없어서 사진 부분은 회색 네모로 채웠습니다
| 활동 기록 화면 | <img src = "https://user-images.githubusercontent.com/79050615/210307503-1066cd7b-4add-48c8-a45a-67db6633ef0e.png" width = 300> |
- Resolved: #20
> [Feat] #20 - ActivityRecordInfo VC UI 구현

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomNavigationBar.swift
- Runnect-iOS/Runnect-iOS/Global/UIComponents/MapView/RNMapView.swift
- Runnect-iOS/Runnect-iOS/Global/UIComponents/MapView/RNStartMarker.swift
- Runnect-iOS/Runnect-iOS/Global/Utils/caculateStatusBarHeight.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/DepartureSearchVC.swift
- CourseDrawingVC UI 구현
- 이를 위해 RNMapView (커스텀한 네이버 지도) 수정
- 핵심 뷰인 지도 그리기 뷰를 구현했습니다.
- 화면 전환이 살짝 밋밋해서 애니메이션을 추가했습니다. (디자인 쪽에서 별로라고 하면 제거 예정)
| 지도 그리기 뷰 | ![Simulator Screen Recording - iPhone 14 - 2023-01-03 at 21 23 54](https://user-images.githubusercontent.com/77267404/210356758-03537800-b140-4436-be43-6743c0540225.gif) |
- Resolved: #24
> [Feat] #24 - CourseDrawingVC UI 구현

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/PrivateCourseListView.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/ScrapCourseListView.swift
- Runnect-iOS/Runnect-iOS/Presentation/Running/VC/CountDownVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunTrackingVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningWaitingVC.swift
- 보관함에서 내가 그린 코스를 선택했을 때 보여줄 지도 뷰 (달리기 대기 뷰)를 구현했습니다.
- 경로선 보이게 하는건 서버 통신 연결하고 서버에서 받은 좌표로 보이도록 구현하겠습니다!
- 다들 화이팅~!!!!
| RunningWaitingVC |  <img src = "https://user-images.githubusercontent.com/77267404/210942277-b5d77799-2f5b-4309-ba9d-70dc6fce2cf0.png" width = 300>  |
- Resolved: #48
> [Feat] #48 - RunningWaitingVC UI

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/ResponseDto/PrivateCourseResponseDto.swift
- Runnect-iOS/Runnect-iOS/Network/Router/CourseStorageRouter/CourseStorageRouter.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CVC/CourseListCVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/PrivateCourseListView.swift
- 보관함에서 내가 그린 코스 API 연결
- 보관함에서 내가 그린 코스 API 연결
| 보관함 |  ![Simulator Screen Recording - iPhone 14 - 2023-01-10 at 18 53 53](https://user-images.githubusercontent.com/77267404/211519201-6f84d92e-ea27-4bea-af28-010d8e2d7f58.gif)  |
- Resolved: #69
> [Feat] #69 - 보관함 내가 그린 코스 API 연결

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/ResponseDto/PrivateCourseResponseDto.swift
- Runnect-iOS/Runnect-iOS/Network/Dto/RunningDto/ResponseDto/CourseDetailResponseDto.swift
- Runnect-iOS/Runnect-iOS/Network/Model/CourseDrawingModel/DepartureLocationModel.swift
- Runnect-iOS/Runnect-iOS/Network/Model/RunningModel/RunningModel.swift
- Runnect-iOS/Runnect-iOS/Network/Router/RunningRouter/RunningRouter.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/Running/VC/CountDownVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningRecordVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningWaitingVC.swift
- 코스 디테일 API 연결
- 보관함에서 내가 그린 코스를 선택하면 API를 호출하여 해당 코스에 맞는 경로 데이터를 받아와 지도에 그려줍니다.
- 이 API 는 추후 다른 곳에서도 courseId를 가지고 경로 정보를 받아올 때 사용할 수 있습니다!
|  API 연결  |  ![Simulator Screen Recording - iPhone 14 - 2023-01-11 at 00 48 22](https://user-images.githubusercontent.com/77267404/211598094-187d6ecf-594f-4a30-84ba-366d335f603f.gif)  |
- Resolved: #74
> [Feat] #74 - 코스 디테일 API 연결

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/ResponseDto/PickedMapListResponseDto.swift
- Runnect-iOS/Runnect-iOS/Network/Router/MyPageRouter/MyPageRouter.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoCollectionView/UploadedCourseInfoCVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
- 업로드한 코스 API 연결
- 🥹
생략
- Resolved: #73
> [Feat] #73 - 업로드한 코스 API 연결

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Network/Router/CourseDiscoveryRouter/CourseSearchingRouter.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseSearchVC.swift
- 코스 검색 API 연결했습니다
- PR Point 1
- Resolved: #76
> [Feat] #76 - 코스 검색 API 연결

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/ResponseDto/PrivateCourseNotUploadedResponseDto.swift
- Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/ResponseDto/PrivateCourseResponseDto.swift
- Runnect-iOS/Runnect-iOS/Network/Router/CourseStorageRouter/CourseStorageRouter.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseUploadVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/MyCourseSelectVC.swift
- 코스 발견에서 코스 업로드를 하기 위해 내가 그린 코스들 중에서 아직 업로드를 하지 않은 코스들을 가져오는 API를 연결했습니다.
- 코스 업로드 VC 로 받아온 CourseModel을 보내도록 했으니 CourseUpload API를 연결할 때 해당 모델에서 id 값을 가져와 업로드를 진행하면 될 것 같습니다~!
| 코스 불러오기 |  ![Simulator Screen Recording - iPhone 14 - 2023-01-11 at 13 03 19](https://user-images.githubusercontent.com/77267404/211715547-185187ab-9fc8-482c-8057-ff7a625aed3c.gif)  |
- Resolved: #79
> [Feat] #79 업로드하지 않은 내가 그린 코스 API 연결

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Global/Utils/RNUtils/RNTimeFormatter.swift
- Runnect-iOS/Runnect-iOS/Network/Dto/MyPageDto/ActivityRecordInfoDto.swift
- Runnect-iOS/Runnect-iOS/Network/Router/MyPageRouter/MyPageRouter.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoTableView/ActivityRecordInfoTVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoCollectionView/UploadedCourseInfoCVC.swift
- 활동 기록 api 연결
- 콘솔창에 constraints 관련한 오류가 계속 떴는데.. 알고보니 스택뷰 안의 요소들 너비, 스택뷰 전체의 너비를 이중으로 설정해 생긴 오류였습니다 ㅋㅋ 아놔 
- 연결 잘 됐는데 자꾸 400 error 떠서 봤더니.. 부호를 반대로 써놨었음.. 아놔 ㅋ
- 인덱싱 하는 방법을 잘 몰라서.. "00:03:40"로 받은 값을 UI에 "0:03:40"으로 나타내야 할 때 -> .suffix(7)로 나타냈는데.. 더 좋은 방법이 있나요..?
생략
- Resolved: #78
> [Feat] #78 - 활동 기록 API 연결

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomButton.swift
- Runnect-iOS/Runnect-iOS/Global/UIComponents/ListEmptyView.swift
- Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/ResponseDto/ScrapCourseResponseDto.swift
- Runnect-iOS/Runnect-iOS/Network/Router/CourseStorageRouter/CourseStorageRouter.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/ScrapCourseListView.swift
- 보관함 스크랩한 코스 API 연결
- 보관함의 스크랩한 코스의 cell을 선택하면 스크랩한 코스 디테일을 보는 뷰(CourseDetailVC)로 넘어가도록 했습니다. 이때, 선택된 코스의 id(courseId)와 publicCourseId를 같이 넘겨주도록 했습니다! CourseDetailVC에서 데이터를 불러오기 위해 서버 통신을 할 때 request로 필요해서 넘겨준거라고 생각하시면 됩니다! 스크랩 코스 상세페이지 API 연결하는 분은 이 Id를 사용해서 서버 통신을 하시면 됩니다..!!!
- 생략
- Resolved: #85
> [Feat] #85 - 스크랩코스 API 연결

- Runnect-iOS/Runnect-iOS/Network/Router/MyPageRouter/MyPageRouter.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/NicknameEditorVC.swift
- 마이페이지 닉네임 변경 API 연결
- 닉네임 수정을 완료한 뒤에 viewWillAppear이 호출되지 않아 delegate 패턴을 썼고 나중에 더 공부해보겠습니다..
| 코스 상세 페이지 | <img src = "https://user-images.githubusercontent.com/79050615/211993572-b6dc29d5-b45d-4598-bd09-fc23494c9bbc.mp4" width = 300>  |
- Resolved: #90
> [Feat] #90 - 마이페이지 닉네임 변경 API 연결

- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseSearchVC.swift
- CourseSearchVC API 연결 완료
- 
- Resolved: #91
> [Feat] #91 - CourseSearchVC API 연결 완료

- Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/ResponseDto/PickedMapListResponseDto.swift
- Runnect-iOS/Runnect-iOS/Network/Router/CourseDetailRouter/UploadedCourseDetailRouter.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseSearchVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CVC/CourseListCVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/ScrapCourseListView.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
- 스크랩 API 연결
- 끝!!!!!!!! (아님)
생략
- Resolved: #97
> [Feat] #97 - 스크랩 API 연결

- Runnect-iOS/Runnect-iOS/Global/Supports/SceneDelegate.swift
- Runnect-iOS/Runnect-iOS/Global/UIComponents/RNAlertVC.swift
- Runnect-iOS/Runnect-iOS/Network/Router/RecordRouter.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoTableView/ActivityRecordInfoTVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
- 마이페이지 러닝 기록 상세뷰 UI 구현
- 러닝기록 삭제 api 연결
- 러닝 기록에서 중복 선택 삭제, 상세 뷰에서 삭제까지 구현했습니다.
- alertvc에서 삭제 버튼 눌렸을 때, delegate를 통해 VC가 알 수 있도록 해보았습니다.
- (왜 안되죠..?) 삭제 이후 테이블뷰가 reload 되지 않는 이유를 모르겠습니다.. 
- 중복 코드가 많아서 지저분한 것 같습니다.. 이후에 수정하겠습니답
- 문제 발견.. 만약에 러닝 기록이 없음 -> 코스 그리기 페이지로 이동 -> hideToTabBar한 상태라 탭바가 업숨 => 어쩌죠잉
| 러닝기록 | <img src = "https://github.com/Runnect/Runnect-iOS/assets/79050615/98245294-4aa7-4df8-b883-a4e3ac0f76a6" width = 300> |
- Resolved: #136
> [Feat] #136 - 마이페이지 러닝 기록 상세뷰 UI와 삭제 api 연결

- Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomNavigationBar.swift
- Runnect-iOS/Runnect-iOS/Network/Router/RecordRouter.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingHomeVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
- 러닝 기록 수정 페이지 UI 및 api 연결
- 수정 페이지 UI 구현 및 api를 연결했습니다.
- 수정 페이지에서 네비바의 이전 버튼을 눌렀을 때, AlertVC가 나오게 하기 위하여 커스텀네비바의 코드를 수정했습니다.
- 수정을 완료하여 버튼을 눌렀을 때, 팝업이 뜨지 않아 뭔가 어색?해 기디에 문의해놓았고 답변 이후 반영하겠습니다.
| 러닝 기록 수정 페이지 | <img src = "https://github.com/Runnect/Runnect-iOS/assets/79050615/32a37592-b891-4f5e-bf85-44d44ea02ff0" width = 300> |
- Resolved: #139
> [Feat] #139 - 러닝 기록 수정 페이지 UI 및 api 연결

- Runnect-iOS/Runnect-iOS/Network/Dto/CourseDetailDto/ResponseDto/UploadedCourseDetailResponseDto.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
- 마이페이지에서 업로드한 코스 목록에서 디테일뷰로 넘어갈 때 데이터가 안들어오는 문제 해결
- CourseDetailVC에 courseId와 publicCourseId를 넘겨줬어야 했는데 그게 없었습니다.
- 서버에서 user의 level을 넘겨줄 때 String으로 주고 있는데 우리 dto에는 Int로 되어 있었습니다.
생략
- Resolved: #147
> [Fix] #147 - 업로드한 코스 디테일뷰 서버통신 실패 해결

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- 리젝 사유였던 위치 정보 권한 텍스트를 더 구체적으로 변경했습니다.
- 
| 동의 화면 | <img src="https://github.com/Runnect/Runnect-iOS/assets/77267404/f162af61-d0a8-4f74-b89e-09bbcfcd6128" width = 300> |
- Resolved: #151
> [Fix] #151 - 위치 정보 권한 텍스트 변경

- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/PrivateCourseListView.swift
- 보관함 편집모드 애니메이션 버그 수정
- 편집 모드를 끝내면 보관함VC와 `privateCourseListView` 둘다 편집 모드를 끈 상태로 UI가 바뀌어야 하는데 후자를 처리하지 않아서 생긴 문제였음
- 따라서 이 부분을 처리하고 editMode의 UI 변경 코드들을 한 곳을 모아(isEditMode) 가독성을 높이고 불필요한 코드를 많이 제거함
- 보관함 뷰에서 이탈했을 때 탭바 위치가 의도하지 않은 위치로 바뀌는 버그를 수정함
| 삭제하기 애니메이션 | ![Simulator Screen Recording - iPhone 14 - 2023-05-28 at 23 06 38](https://github.com/Runnect/Runnect-iOS/assets/77267404/a9cb51e6-2363-42c7-af9f-fc5b2e2d5ca8) |
- Resolved: #155
> [Fix] #155 - 보관함 편집모드 애니메이션 버그 수정

- Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseEditVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/MyCourseSelectVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/PrivateCourseListView.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/SettingVC.swift
- 현재 발견된 버그들을 수정했습니다.
- 피그마 상 UI와 달라보이는 부분들의 레이아웃 간격 등을 작게 수정했습니다.
- 코스 공유 -> 상세 페이지 -> 내가 올린 코스일 경우 수정 페이지: 완료 버튼 눌렀을 때 api 요청을 보내고, 저장 없이 뒤로가기를 할 경우 alert 팝업이 뜨도록 코드를 수정했습니다. 또한, 같은 코스에 대하여 두 번 수정이 불가능한 부분, 완료 버튼 활성화 로직을 수정했습니다.
- 코스 공유 -> 상세 페이지: 알 수 없음 유저에 대해서 UI가 다르게 보일 수 있도록 수정했습니다.
- 내 러닝 기록 수정에서 api 요청이 제대로 되지 않아 확인해보니, 해당 함수를 테스트용으로 주석 처리 해놓은 것을 해제하지 않아 생기 ㄴ문제였습닏다.. (ㅋ)
| 코스 공유  | <img src = "https://github.com/Runnect/Runnect-iOS/assets/79050615/81215d60-e23d-4be7-9b38-6e17c5337a81" width = 300>  |
- Resolved: #154
> [Fix] #154 - 1차 릴리즈 QA 2차 반영

- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/AdImageCollectionViewCell.swift
- 배너가 수동으로 슬라이드했을 때 페이지컨트롤이 되지 않는 부분을 해결했습니다. 수동,자동 다 페이지 컨트롤이 업데이트됩니다
- 리팩 필요,,
- Resolved: #153
> [Fix] #153 - 1차릴리즈이슈대응

- Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseEditVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
- CourseEdit 뷰에서 이미지에 공백을 주어 생긴 이슈를 해결했습니다
- Resolved: #159
> [Fix] - 이미지 이슈 해결

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Global/UIComponents/ShadowView.swift
- Runnect-iOS/Runnect-iOS/Network/Service/Providers.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
- 코스 발견 뷰 하단에 업로드 하기 버튼에 그림자를 추가 했습니다.
- 업데이트 심사를 위한 빌드 세팅을 진행했습니다.
- 기존 인증서를 파기하고 새로 받아서 기존에 가지고 계신 인증서는 이제 동작하지 않을거에요 지워주시면 됩니다..!
| 그림자 | <img width="300" alt="image" src="https://github.com/Runnect/Runnect-iOS/assets/77267404/91b94e9b-5537-4e4e-8f53-53d0b4085a60"> |
- Resolved: #161
> [Feat] #161 - 업로드 버튼 그림자

- .gitignore
- Runnect-iOS/Gemfile
- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Info.plist
- Runnect-iOS/fastlane/Appfile
- Runnect-iOS/fastlane/Fastfile
- Runnect-iOS/fastlane/Matchfile
- Runnect-iOS/fastlane/README.md
- fastlane을 도입했습니다
- 이제 fastlane match를 통해 쉽게 인증서 관리가 가능합니다.
- 새로운 팀원이 왔을 때 저번처럼 카톡으로 제가 인증서를 드리지 않아도 본인이 직접 터미널에 명령어를 입력하면 Github private 레포지토리에 제가 올려둔 인증서들이 자동으로 다운로드 되는 원리입니다.
- fastlane은 CI/CD 툴입니다. [참고](https://docs.fastlane.tools/#)
- lane 명령어를 생성하고 fastlane에서 제공하는 함수들을 활용하여 원하는 기능을 구현할 수 있습니다.
- 인증서를 다운받는 `match_read_only`
- 프로젝트 버전을 설정하는 `set_version`
- 테스트플라이트 업로드를 해주는 `upload_testflight`
이렇게 3가지를 만들어 두었으며 필요하다면 추가적으로 만들어서 사용하시면 됩니다!!
지금은 인증서를 최신화하는 `match_read_only`만 사용해도 무관합니다.
우선 Github ssh 등록은 안했다면 등록 해주세요 [가이드](https://docs.github.com/ko/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)
[Fastlane 공식 가이드 참고](https://docs.fastlane.tools/getting-started/ios/setup/)
1. 터미널 켜서 Runnect 프로젝트 폴더로 이동
2. `xcode-select --install` 실행 …
> [Feat] #167 - fastlane 도입

- Runnect-iOS/Runnect-iOS/Global/Utils/setImage.swift
- Runnect-iOS/Runnect-iOS/Info.plist
- 작업 내용 1
Xcode 가 15로 버전업 되면서 원래 코드가 디버깅이 안됩니다.
그래서 약간 수정을 하였습니다.
Xcode 14.x 버전에서도 돌아가니 꼭 업데이트 안하셔도됩니다.
- ATS(App Transport Sercurity) 문제 -> info.plist 수정
- Kingfisher -> 명확하게 어떤 클래스인지 수정
링크 참고
https://thingjin.tistory.com/entry/iOS-Xcode-15-Kingfisher-%EC%97%90%EC%84%9C%EC%9D%98-ImageResource-%EC%9D%B4%EC%8A%88-%ED%95%B4%EA%B2%B0
info.plist
파일에는 소스로 보여서 뭐가 바뀐지 모를텐데 저 부분을 추가 했어요!
- Resolved: #184
> [Fix] #184 - Xcode 15 버전 코드 수정

- Runnect-iOS/Runnect-iOS/Global/UIComponents/RNAlertVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/SettingVC.swift
마이페이지 VC
- 카카오톡 채널 문의 기능추가 + ` 러닝 기록` `목표 보상`  위치 수정
- 설정 -> 문의 및 신고하기 제거 (카카오톡 문의 기능 추가 되어서 제거)
-  figma 알림 메세지 변경 "예"-> "네" 
- 위치 변경에 대한 레이아웃 조정과 코드 위치를 조금 수정 하였습니다.
|    MyPageVC   |   SettingVC   |  RNAlertVC  | 
| :-------------: | :----------: | :-------------: |
| <img width="350" alt="image" src="https://github.com/Runnect/Runnect-iOS/assets/88179341/1411994b-3c0b-4dd4-92ba-2a27edb417d4"> | <img width="350" alt="image" src="https://github.com/Runnect/Runnect-iOS/assets/88179341/4738214b-f834-4f4f-949e-80d9e1e8bea1">  | ![image](https://github.com/Runnect/Runnect-iOS/assets/88179341/95ce6228-db14-4cc4-a82c-6c15fe71c27d) |
- Resolved: #187
> [Feat] #187 - 마이 페이지 수정 및 기능 구현

- Runnect-iOS/Runnect-iOS/Network/Router/PublicCourseRouter.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
- ⭐️코스 발견의 데이터 받아오는 API 가 변경되는 것⭐️ 이 있었습니다.
그에 맞게 라우터 수정과 Pagination 로직을 추가 했습니다.
- PublicCourseRouter.getCourseData 에 parameter `pageNo` 추가
저희 API를 보시면 디폴트가 pageNo = 1 로 수정 되었고 직접 추가를 해줘야하기 때문에 변경 하였습니다.
- `scrollViewDidScroll()` 메서드 추가 ⭐️⭐️
- `viewWillAppear()` 로직 추가
- 이해 안 되는 부분이 있을까봐 주석을 달아 놨습니다.
코드 리뷰 후 정말 필요하다 싶은 것 빼고는 주석 지우고 머지 할 생각입니다.
- `Pagination` 의 로직을 구현했는데 아래 블로그에 정리해놨습니다
이해 안 될 수도 있는데 안된다면 따로 디스코드 요청 바랍니다!
[Pagination 정리](https://thingjin.tistory.com/entry/iOS-%EB%8D%B0%EC%9D%B4%ED%84%B0-%ED%8E%98%EC%9D%B4%EC%A7%95-Pagination-in-UIKit-ColletionView)
- 요약
courseList 의 전체 개수가 pageNo x 24 보다 작다면 데이터를 다 불러왔다고 생각하여 페이지네이션을 끝내는 로직을 구현 했습니다.
24를 곱한 이유는 우리의 API 가 page 당 24개씩 불러오기 때문입니다.
괜찮은 로직이 생각나면 리뷰 부탁드립니다.
| 🕒 페이징 도입 전 | 🕓 페이징 도입 후 |
| …
> [Feat] #183 - 코스 발견 pagination

- Runnect-iOS/Podfile
- Runnect-iOS/Podfile.lock
- Runnect-iOS/Runnect-iOS/Info.plist
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
- 채널 문의로 가는 플로우를 간소화 하였습니다.
API 사용하기 전에는 "카카오톡에서 이 페이지를 열겠습니까" 라는 팝업 없었습니다.
- 카카오 SDK Talk 으로 조금 수정 하였습니다.
|    구현 내용    |   
| :-------------: | 
| 마이페이지 카카오톡 채널 문의 | 
https://github.com/Runnect/Runnect-iOS/assets/88179341/5f6d3781-4ec4-4dd8-bb84-39516ea97701
- Resolved: #193
> [Fix] #193 - 카카오톡 채널 문의 기능을 수정 하였습니다.

- Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
- 나의 업로드한 코스 삭제 기능을 사용했을때, 
`삭제 -> 뷰 새로고침` 으로 로직이 되어야하는데
`뷰 새로고침 -> 삭제` 순서가 되어버려서 나의 업로드한 코스가 새로고침이 안되는 오류가 발생 하였습니다. 
(이벤트 시점 문제)
- 삭제 후 뷰 이동이 안되는 부분도 해결하였습니다 -> #192 
- deleteCourse에 동기 처리로 0.1초의 텀을 두었습니다.
- 또한 DispatchQueue.main.asyncAfter() 쓰는 게 좋은 코드인지? 생각해 봐야겠습니다.
- ❌ ver 2.0.0 전 (코스 1개 삭제 시 코스 1개 그대로 남아 있고 뷰 이동도 처리되지 않음)
(UI도 업데이트전 ^^..)
https://github.com/Runnect/Runnect-iOS/assets/88179341/1a682c09-336c-4d9a-8ddb-28b3ccfe0be3 
---
- ✅ ver 2.0.0 후 ( 코스 2개 에서 1개 새로고침 + 뷰 이동 처리 )
https://github.com/Runnect/Runnect-iOS/assets/88179341/1a1c051a-00b0-4781-b3cd-dc32bbaa2f2f 
- Resolved: #196
> [Fix] #196 - 코스 삭제 이벤트 시점을 수정 하였습니다.

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomBottomSheetVC.swift
- textField가 있는 바텀시트 개발
- type 형식으로  Custom 개발 가능
- image
- textField
- 상황에 따라 시트 부분이 아닌 부분을 입력 시 어떤 action으로 작동할지 필요
- type 형식을 받아 템플릿을 제공해 주는 코드라서 확장성을 요구하는 코드 구조
- 다양한 기능을 전부 구현하진 않아서 기능 요구사항이 들어오면 좀 더 확장을 해야 합니다.
|    바텀 시트  | 
| :-------------: |
- Resolved: #200
> [Feat] #200 - 커스텀 바텀 시트 개발 하였습니다.

- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/MyCourseSelectVC.swift
- divide View 추가
- 안내문구 View 추가
- 안내문구 Label 추가
- 컬렉션뷰 레이아웃 일부 조정
- `MyCourseSelectVC()`  에서 작업을 하였습니다.
- 변경된 레이아웃 정도만 확인 해주세요.
|    코스가 있을 때    |   코스가 없을 때  |
| ![IMG_4515](https://github.com/Runnect/Runnect-iOS/assets/88179341/42f904ce-2e1b-43ea-891b-753834017180) |  ![IMG_4514](https://github.com/Runnect/Runnect-iOS/assets/88179341/4a3b13d1-644b-4e05-b732-3d855d19d718) |
- Resolved: #202
> [Add] #202 - 코스발견 불러오기에 안내문구를 추가 하였습니다.

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomBottomSheetVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
- 크게 바뀐 부분은 없고, 요청한 `바텀 시트의 위치`나, `디자인 코드`를 수정을 하였습니다.
- 코드를 수정하다가, 네이밍이 적절하지 못한 부분을 발견하여 수정 하였습니다.
- `짧은 동적링크`로 변환하는 부분도 코드의 수정이 이루어졌습니다.
- 키보드가 올라갈 시 바텀 시트의 위치
- 뒤로 가는 플로우
- 공유 기능 코드의 개선
| 코스 이름 입력 뷰 | <img src="https://github.com/Runnect/Runnect-iOS/assets/88179341/681e09e1-72f5-433b-accb-e8a4665cc679" width="195" height="422"> |
- Resolved: #209
> [Refactor] #209 - 코스 공유와, 커스텀 바텀시트 부분을 수정 하였습니다.

- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
- 드롭 다운으로 메뉴 변경
- 예전 코드 약간 수정
- 키보드 안올라가는 이슈
- 키보드 관련 로직 추가 
- 텍스트 필드의 텍스트(`TextField.text`)를 눌러야 `.editingChanged` 가 되는데.. 왜 텍스트 필드를 누르면 안 될까요..? ,, 기존 코드의 어떤 문제점이 있을지 ... !?
- 기존 코드에서 키보드를 안 올린 것 이 일부러 안 올린 건지..? 궁금하네요,,, 
- 어떻게 생각하시는지?? ㅎㅎ
| 러닝 기록 상세 페이지 | <img src="https://github.com/Runnect/Runnect-iOS/assets/88179341/84bda5e9-c806-441f-a2a6-04eb5296b547" width="195" height="422"> |
- Resolved: #212
> [Feat] #212 - 러닝 기록 상세페이지 메뉴 변경

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Info.plist
- 앱 이전 작업
- x
| ex. 로그인 화면 | 파일첨부바람 |
- Resolved: #232
> [Setting] #232 - 계정 이전 작업

- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/ResponseDto/PrivateCourseNotUploadedResponseDto.swift
- Runnect-iOS/Runnect-iOS/Network/Dto/MyPageDto/MyUploadedCourseResponseDto.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseUploadVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/MyCourseSelectVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
- 코스 업로드 : 피드 새로고침 `(refresh)`
- 코스 삭제 : 피드 새로고침 `(refresh)`
- 코스 스크랩 : 해당 PR 에서 구현 #213 
- 서버측 Dto 변경으로 인한 Dto 추가 작업
- PR Point 1
- Resolved: #226
> [Feat] #226 - 코스 발견 피드에서의 이벤트 처리들을 추가 해주었습니다.

- Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseUploadVC.swift
- 코스 주소 부분을 동까지 나오게 수정 하였습니다.
- 값이 nil인 값이 들어올 수 있기 때문에 CompactMap으로 문자열을 잇는 작업을 해주었습니다.
| ex. 로그인 화면 | 파일첨부바람 |
- Resolved: #235
> [Add] #235 - 코스 주소 세부 사항 추가

- Runnect-iOS/Podfile
- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Global/Supports/AppDelegate.swift
- remote config 추가
- 업데이트 alert 추가
- alert 추가 시점은 appDelegate에서 정의했습니다
| ex. 로그인 화면 | <img src="https://github.com/Runnect/Runnect-iOS/assets/54045865/5b7f88df-32b6-4a24-a9a0-9f319567a9bc" width=300 /> |
- Resolved: #206
> [Feat] #206 - remote config 추가했습니다

- .gitignore
- Runnect-iOS/.bundle/config
- Runnect-iOS/Gemfile
- Runnect-iOS/Podfile
- Runnect-iOS/Podfile.lock
- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomBottomSheetVC.swift
- Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomNavigationBar.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CVC/CourseListCVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningWaitingVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/Splash/VC/SplashVC.swift
- Xcode16 업데이트 및 외부 라이브러리 업데이트 했습니다.
- 이미지 깨지는 문제 해결 했습니다.
- SwiftLint 추가된 경고 해결 했습니다.
- cocoaPods 사용으로 인해 라이브러리 `네이버 맵 Legacy` 로 변경 해주었습니다.
- `Gemfile`, `Podfile` 수정했습니다.
- `scaleAspectFill` 을 사용하여 원본의 비율을 유지하게 했고, 넘어가는 이미지는 `clipsToBounds`로 바운더리 범위를 제한해줬습니다.
- Xcode 16으로 업데이트하면서 생긴 Lint 경고를 없앴습니다.
|     수정 전   |   수정 후   |
|  ![IMG_0094](https://github.com/user-attachments/assets/cfc0e6f0-5889-4449-a0fe-1b6f0c9b4819) |  ![IMG_0095](https://github.com/user-attachments/assets/b0a3359e-a6c4-4884-b20a-e4013bdc76e5) |
|     수정 전   |   수정 후   |
| ![IMG_0097](https://github.com/user-attachments/assets/2c84024b-8ca3-4a91-9bc8-f86ffcb4448e) |  ![IMG_0099](https://github.com/user-attachments/assets/85a1edb4-5375-4f06-a3a0-385a15 …
> [Setting] #268 - Xcode16 버전 업데이트 및 이미지 깨지는 문제 해결 했습니다.

- README.md
- Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
- Runnect-iOS/Runnect-iOS/Global/Extension/UIKit+/UIButton+.swift
- Runnect-iOS/Runnect-iOS/Global/Supports/SceneDelegate.swift
- Runnect-iOS/Runnect-iOS/Global/Utils/RNUtils/UserManager.swift
- Runnect-iOS/Runnect-iOS/Info.plist
- Runnect-iOS/Runnect-iOS/Network/Service/NetworkProvider.swift
- Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
- Runnect-iOS/Runnect-iOS/Presentation/SignIn/VC/NickNameSetUpVC.swift
- 공유링크를 받고, 방문자 모드일때 public link 사용 가능 하게 수정
| 공유기능(방문자) |  <img src = "https://github.com/user-attachments/assets/b99f406f-b2be-4015-93bd-fda00406fbcc" width = "50%" height = "50%"> |
- Resolved: #272
> [Fix] #272 - 공유기능개선 및 2.2.0 앱스토어 배포
